"""add recoverable to generation logs

Revision ID: 004647ae9c6a
Revises: 2c7243e2ce79
Create Date: 2026-07-26 14:47:46.935203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004647ae9c6a'
down_revision: Union[str, None] = '2c7243e2ce79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_logs', sa.Column('recoverable', sa.Boolean(), server_default='0', nullable=True))
    op.create_index(op.f('ix_generation_logs_recoverable'), 'generation_logs', ['recoverable'], unique=False)
    # Update historical data to be recoverable=True
    op.execute("UPDATE generation_logs SET recoverable = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_logs_recoverable'), table_name='generation_logs')
    op.drop_column('generation_logs', 'recoverable')
    # ### end Alembic commands ###
