"""remove_forum_video_metadata_fields

Revision ID: 035a301b387a
Revises: c090144c0f79
Create Date: 2026-06-09 02:08:54.191500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035a301b387a'
down_revision: Union[str, None] = 'c090144c0f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    return table_name in set(sa.inspect(op.get_bind()).get_table_names())


def _column_exists(table_name: str, column_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    return column_name in {col["name"] for col in sa.inspect(op.get_bind()).get_columns(table_name)}


def _drop_column_if_exists(table_name: str, column_name: str) -> None:
    if _column_exists(table_name, column_name):
        op.drop_column(table_name, column_name)


def upgrade() -> None:
    _drop_column_if_exists('forum_videos', 'duration')
    _drop_column_if_exists('forum_videos', 'thumbnail_url')
    _drop_column_if_exists('forum_videos', 'published_at')
    _drop_column_if_exists('forum_videos', 'description')
    _drop_column_if_exists('forum_videos', 'title')
    _drop_column_if_exists('forum_videos', 'views')
    _drop_column_if_exists('forum_videos', 'channel_name')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_videos', sa.Column('channel_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('forum_videos', sa.Column('views', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('forum_videos', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('forum_videos', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('forum_videos', sa.Column('published_at', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('forum_videos', sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('forum_videos', sa.Column('duration', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
