"""add aux_model_version to generation_logs

Revision ID: 2c7243e2ce79
Revises: 76e0bf44aa23
Create Date: 2026-07-26 13:10:12.787652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7243e2ce79'
down_revision: Union[str, None] = '76e0bf44aa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_logs', sa.Column('aux_model_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###
    
    # Split and migrate historical data
    op.execute("""
        UPDATE generation_logs
        SET 
          aux_model_version = split_part(model_version, ' + ', 1),
          model_version = split_part(model_version, ' + ', 2)
        WHERE model_version LIKE '% + %';
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_logs', 'aux_model_version')
    # ### end Alembic commands ###
