"""add minecraft_skin_url to users

Revision ID: 6dfe98a00da2
Revises: b75f3b39ad02
Create Date: 2026-06-09 10:59:10.350665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dfe98a00da2'
down_revision: Union[str, None] = 'b75f3b39ad02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('minecraft_skin_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'minecraft_skin_url')
    # ### end Alembic commands ###
