"""remove edit_source_type from generation logs

Revision ID: a320925161ce
Revises: 004647ae9c6a
Create Date: 2026-07-26 15:20:42.992098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a320925161ce'
down_revision: Union[str, None] = '004647ae9c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_logs', 'edit_source_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_logs', sa.Column('edit_source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
