"""create_credit_logs_table

Revision ID: ae9ec0759716
Revises: d8b2604af42e
Create Date: 2026-07-08 10:21:02.199074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9ec0759716'
down_revision: Union[str, None] = 'd8b2604af42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_logs',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_logs_created_at'), 'credit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_logs_id'), 'credit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_credit_logs_user_id'), 'credit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_logs_user_id'), table_name='credit_logs')
    op.drop_index(op.f('ix_credit_logs_id'), table_name='credit_logs')
    op.drop_index(op.f('ix_credit_logs_created_at'), table_name='credit_logs')
    op.drop_table('credit_logs')
    # ### end Alembic commands ###
