"""add_forum_videos

Revision ID: c090144c0f79
Revises: 8d5fb3684bc5
Create Date: 2026-06-09 02:00:22.828929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c090144c0f79'
down_revision: Union[str, None] = '8d5fb3684bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    return table_name in set(sa.inspect(op.get_bind()).get_table_names())


def _index_exists(table_name: str, name: str) -> bool:
    return name in {idx["name"] for idx in sa.inspect(op.get_bind()).get_indexes(table_name)}


def _create_index_if_missing(table_name: str, name: str, columns: list[str]) -> None:
    if not _index_exists(table_name, name):
        op.create_index(name, table_name, columns, unique=False)


def upgrade() -> None:
    if not _table_exists('forum_videos'):
        op.create_table('forum_videos',
        sa.Column('id', sa.String(length=16), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('youtube_id', sa.String(length=50), nullable=False),
        sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
        sa.Column('channel_name', sa.String(length=100), nullable=True),
        sa.Column('views', sa.String(length=50), nullable=True),
        sa.Column('duration', sa.String(length=20), nullable=True),
        sa.Column('published_at', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    _create_index_if_missing('forum_videos', 'ix_forum_videos_created_at', ['created_at'])
    _create_index_if_missing('forum_videos', 'ix_forum_videos_id', ['id'])
    _create_index_if_missing('forum_videos', 'ix_forum_videos_youtube_id', ['youtube_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_videos_youtube_id'), table_name='forum_videos')
    op.drop_index(op.f('ix_forum_videos_id'), table_name='forum_videos')
    op.drop_index(op.f('ix_forum_videos_created_at'), table_name='forum_videos')
    op.drop_table('forum_videos')
    # ### end Alembic commands ###
