"""Add cloud spending holds without resetting any Space resources."""
from alembic import op
import sqlalchemy as sa
revision = 'c7a4d8e90512'
down_revision = 'b6d1e4f80237'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_credit_authorizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('world_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('request_digest', sa.LargeBinary(length=32), nullable=False),
    sa.Column('max_credits', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_credits >= 0 AND max_credits <= 168', name='ck_space_credit_budget'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_credit_authorizations_user_id'), 'space_credit_authorizations', ['user_id'], unique=False)
    op.create_index('ix_space_credit_entity', 'space_credit_authorizations', ['world_id', 'entity_id'], unique=False)
    op.create_table('space_credit_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('authorization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('reserved','captured','released')", name='ck_space_credit_reservation_state'),
    sa.ForeignKeyConstraint(['authorization_id'], ['space_credit_authorizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_credit_reservations_authorization_id'), 'space_credit_reservations', ['authorization_id'], unique=False)
    op.create_index('ix_space_credit_user_state', 'space_credit_reservations', ['user_id', 'state'], unique=False)
    # ### end Alembic commands ###
    op.add_column("space_world_entities", sa.Column("hosting_authorization_id", sa.String(36), nullable=True))



def downgrade():
    op.drop_column("space_world_entities", "hosting_authorization_id")
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_space_credit_user_state', table_name='space_credit_reservations')
    op.drop_index(op.f('ix_space_credit_reservations_authorization_id'), table_name='space_credit_reservations')
    op.drop_table('space_credit_reservations')
    op.drop_index('ix_space_credit_entity', table_name='space_credit_authorizations')
    op.drop_index(op.f('ix_space_credit_authorizations_user_id'), table_name='space_credit_authorizations')
    op.drop_table('space_credit_authorizations')
    # ### end Alembic commands ###
