"""add_credits_and_last_login_date_to_user

Revision ID: d8b2604af42e
Revises: 6dfe98a00da2
Create Date: 2026-07-08 10:11:13.159433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b2604af42e'
down_revision: Union[str, None] = '6dfe98a00da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_login_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_date')
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###
